export const countries = [ 
  {name: "Afghanistan", code: "AF"}, 
  {name: "Åland Islands", code: "AX"}, 
  {name: "Albania", code: "AL"}, 
  {name: "Algeria", code: "AG"}, 
  {name: "American Samoa", code: "AQ"}, 
  {name: "Andorra", code: "AN"}, 
  {name: "Angola", code: "AO"}, 
  {name: "Anguilla", code: "AV"}, 
  {name: "Antigua and Barbuda", code: "AC"}, 
  {name: "Argentina", code: "AR"}, 
  {name: "Armenia", code: "AM"}, 
  {name: "Aruba", code: "AA"}, 
  {name: "Australia", code: "AU"}, 
  {name: "Austria", code: "AT"}, 
  {name: "Azerbaijan", code: "AJ"}, 
  {name: "Bahamas", code: "BF"}, 
  {name: "Bahrain", code: "BA"}, 
  {name: "Bangladesh", code: "BG"}, 
  {name: "Barbados", code: "BB"}, 
  {name: "Belarus", code: "BO"}, 
  {name: "Belgium", code: "BE"}, 
  {name: "Belize", code: "BH"}, 
  {name: "Benin", code: "BN"}, 
  {name: "Bermuda", code: "BD"}, 
  {name: "Bhutan", code: "BT"}, 
  {name: "Bolivia", code: "BL"}, 
  {name: "Bosnia and Herzegovina", code: "BK"}, 
  {name: "Botswana", code: "BC"},  
  {name: "Brazil", code: "BR"}, 
  {name: "Brunei", code: "BX"}, 
  {name: "Bulgaria", code: "BU"}, 
  {name: "Burkina Faso", code: "UV"}, 
  {name: "Burundi", code: "BY"}, 
  {name: "Cambodia", code: "CB"}, 
  {name: "Cameroon", code: "CM"}, 
  {name: "Canada", code: "CA"}, 
  {name: "Cabo Verde", code: "CV"}, 
  {name: "Cayman Islands", code: "CJ"}, 
  {name: "Central African Republic", code: "CT"}, 
  {name: "Chad", code: "CD"}, 
  {name: "Chile", code: "CI"}, 
  {name: "China", code: "CH"}, 
  {name: "Colombia", code: "CO"}, 
  {name: "Comoros", code: "CN"}, 
  {name: "Democratic Republic of Congo", code: "CG"}, 
  {name: "Costa Rica", code: "CS"}, 
  {name: "Cote D'Ivoire", code: "IV"}, 
  {name: "Croatia", code: "HR"}, 
  {name: "Cuba", code: "CU"}, 
  {name: "Cyprus", code: "CY"}, 
  {name: "Czech Republic", code: "EZ"}, 
  {name: "Denmark", code: "DA"}, 
  {name: "Djibouti", code: "DJ"}, 
  {name: "Dominica", code: "DO"}, 
  {name: "Dominican Republic", code: "DR"}, 
  {name: "Ecuador", code: "EC"}, 
  {name: "Egypt", code: "EG"}, 
  {name: "El Salvador", code: "ES"}, 
  {name: "Equatorial Guinea", code: "EK"}, 
  {name: "Eritrea", code: "EN"}, 
  {name: "Estonia", code: "EE"}, 
  {name: "Ethiopia", code: "ET"}, 
  {name: "Falkland Islands (Malvinas)", code: "FK"}, 
  {name: "Faroe Islands", code: "FO"}, 
  {name: "Fiji", code: "FJ"}, 
  {name: "Finland", code: "FI"}, 
  {name: "France", code: "FR"}, 
  {name: "French Polynesia", code: "FP"},
  {name: "Gabon", code: "GB"}, 
  {name: "Gambia", code: "GA"}, 
  {name: "Georgia", code: "GG"}, 
  {name: "Germany", code: "GM"}, 
  {name: "Ghana", code: "GH"}, 
  {name: "Gibraltar", code: "GI"},
  {name: "Greece", code: "GR"}, 
  {name: "Greenland", code: "GL"},
  {name: "Grenada", code: "GJ"}, 
  {name: "Guam", code: "GQ"},
  {name: "Guatemala", code: "GT"}, 
  {name: "Guinea", code: "GV"}, 
  {name: "Guinea-Bissau", code: "PU"}, 
  {name: "Guyana", code: "GY"}, 
  {name: "Haiti", code: "HA"}, 
  {name: "Vatican", code: "VT"},
  {name: "Honduras", code: "HO"}, 
  {name: "Hong Kong", code: "HK"}, 
  {name: "Hungary", code: "HU"}, 
  {name: "Iceland", code: "IC"}, 
  {name: "India", code: "IN"}, 
  {name: "Indonesia", code: "ID"}, 
  {name: "Iran", code: "IR"}, 
  {name: "Iraq", code: "IZ"}, 
  {name: "Ireland", code: "EI"}, 
  {name: "Isle of Man", code: "IM"}, 
  {name: "Israel", code: "IS"}, 
  {name: "Italy", code: "IT"}, 
  {name: "Jamaica", code: "JM"}, 
  {name: "Japan", code: "JA"}, 
  {name: "Jordan", code: "JO"}, 
  {name: "Kazakhstan", code: "KZ"}, 
  {name: "Kenya", code: "KE"}, 
  {name: "Kiribati", code: "KR"}, 
  {name: "North Korea", code: "KN"}, 
  {name: "South Korea", code: "KS"}, 
  {name: "Kuwait", code: "KU"}, 
  {name: "Kyrgyzstan", code: "KG"}, 
  {name: "Laos", code: "LA"}, 
  {name: "Latvia", code: "LG"}, 
  {name: "Lebanon", code: "LE"}, 
  {name: "Lesotho", code: "LT"}, 
  {name: "Liberia", code: "LI"}, 
  {name: "Libya", code: "LY"}, 
  {name: "Liechtenstein", code: "LS"}, 
  {name: "Lithuania", code: "LH"}, 
  {name: "Luxembourg", code: "LU"}, 
  {name: "Macao", code: "MC"},
  {name: "North Macedonia", code: "MK"},
  {name: "Madagascar", code: "MA"}, 
  {name: "Malawi", code: "MI"}, 
  {name: "Malaysia", code: "MY"}, 
  {name: "Maldives", code: "MV"}, 
  {name: "Mali", code: "ML"}, 
  {name: "Malta", code: "MT"}, 
  {name: "Marshall Islands", code: "RMM"}, 
  {name: "Mauritania", code: "MR"}, 
  {name: "Mauritius", code: "MP"}, 
  {name: "Mexico", code: "MX"}, 
  {name: "Micronesia", code: "FM"}, 
  {name: "Moldova", code: "MD"}, 
  {name: "Monaco", code: "MM"}, 
  {name: "Mongolia", code: "MG"}, 
  {name: "Montserrat", code: "MH"},
  {name: "Morocco", code: "MO"}, 
  {name: "Mozambique", code: "MZ"}, 
  {name: "Myanmar", code: "BM"}, 
  {name: "Namibia", code: "WA"}, 
  {name: "Nauru", code: "NR"}, 
  {name: "Nepal", code: "NP"}, 
  {name: "Netherlands", code: "NL"}, 
  {name: "New Caledonia", code: "NC"}, 
  {name: "New Zealand", code: "NZ"}, 
  {name: "Nicaragua", code: "NU"}, 
  {name: "Niger", code: "NG"}, 
  {name: "Nigeria", code: "NI"}, 
  {name: "Northern Mariana Islands", code: "CQ"},
  {name: "Norway", code: "NO"}, 
  {name: "Oman", code: "MU"}, 
  {name: "Pakistan", code: "PK"}, 
  {name: "Palau", code: "PS"}, 
  {name: "Palestine", code: "PALESTINE"},
  {name: "Panama", code: "PM"}, 
  {name: "Papua New Guinea", code: "PP"}, 
  {name: "Paraguay", code: "PA"}, 
  {name: "Peru", code: "PE"}, 
  {name: "Philippines", code: "RP"}, 
  {name: "Poland", code: "PL"}, 
  {name: "Portugal", code: "PO"}, 
  {name: "Puerto Rico", code: "RQ"},
  {name: "Qatar", code: "QA"}, 
  {name: "Romania", code: "RO"}, 
  {name: "Russia", code: "RS"}, 
  {name: "Rwanda", code: "RW"}, 
  {name: "Saint Helena", code: "SH"},
  {name: "Saint Kitts and Nevis", code: "SC"}, 
  {name: "Saint Lucia", code: "ST"}, 
  {name: "Saint Pierre and Miquelon", code: "SB"},
  {name: "Saint Vincent and the Grenadines", code: "VC"},
  {name: "Samoa", code: "WS"}, 
  {name: "San Marino", code: "SM"}, 
  {name: "Sao Tome and Principe", code: "TP"}, 
  {name: "Saudi Arabia", code: "SA"}, 
  {name: "Senegal", code: "SG"}, 
  {name: "Serbia", code: "RI"}, 
  {name: "Seychelles", code: "SE"}, 
  {name: "Sierra Leone", code: "SL"}, 
  {name: "Singapore", code: "SN"}, 
  {name: "Slovakia", code: "LO"}, 
  {name: "Slovenia", code: "SI"}, 
  {name: "Solomon Islands", code: "BP"}, 
  {name: "Somalia", code: "SO"}, 
  {name: "South Africa", code: "SF"}, 
  {name: "Spain", code: "SP"}, 
  {name: "Sri Lanka", code: "CE"}, 
  {name: "Sudan", code: "SU"},
		{name: "South Sudan", code: "OD"}, 
  {name: "Suriname",code: "NS"},
  {name: "Sweden", code: "SW"}, 
  {name: "Switzerland", code: "SZ"}, 
  {name: "Syria", code: "SY"}, 
  {name: "Taiwan", code: "TW"},
  {name: "Tajikistan", code: "TI"}, 
  {name: "Tanzania", code: "TZ"}, 
  {name: "Thailand", code: "TH"}, 
  {name: "Timor-Leste", code: "TT"}, 
  {name: "Togo", code: "TO"}, 
  {name: "Tokelau", code: "TL"},
  {name: "Tonga", code: "TN"}, 
  {name: "Trinidad and Tobago", code: "TD"}, 
  {name: "Tunisia", code: "TS"}, 
  {name: "Turkey", code: "TU"}, 
  {name: "Turkmenistan", code: "TX"}, 
  {name: "Turks and Caicos Islands", code: "TK"},
  {name: "Tuvalu", code: "TV"}, 
  {name: "Uganda", code: "UG"}, 
  {name: "Ukraine", code: "UP"}, 
  {name: "United Arab Emirates", code: "AE"}, 
  {name: "United Kingdom", code: "UK"}, 
  {name: "United States", code: "US"}, 
  {name: "Uruguay", code: "UY"}, 
  {name: "Uzbekistan", code: "UZ"}, 
  {name: "Vanuatu", code: "NH"}, 
  {name: "Venezuela", code: "VE"}, 
  {name: "Vietnam", code: "VM"}, 
  {name: "British Virgin Islands", code: "VI"},
  {name: "U.S. Virgin Islands", code: "VQ"},
  {name: "Wallis and Futuna", code: "WF"},
  {name: "Yemen", code: "YM"}, 
  {name: "Zambia", code: "ZA"}, 
  {name: "Zimbabwe", code: "ZI"} 
];